### ISSUE TITLE
`redirectUri` not processed when Activity gets evicted

### ISSUE THREAD

**Issue by uliluckas** [kalinjul/kotlin-multiplatform-oidc#23]
I have been experimenting with KMM oauth login and ran into a problem on Android when "Don't keep Activities" is selected in developer settings.

In that case, `factory.createAuthFlow(client).getAccessToken()` will suspend forever and not be resumed when the redirectUri call comes in.

This is **relevant beyond the "Don't keep Activities" scenario** as activities can also be destroyed under memory pressure. Setting "Don't keep Activities" only makes the issue reproducible.

Thanks for your work and for any feedback.

**Comment by kalinjul** [comment]
Hi, thanks for your feedback.
I'm using an ActivityResultContract to start the Auth Flow, and I'm not quite sure what happens when the App's Activity is destroyed.
I will look into that - if you have any suggestions let me know.

**Comment by uliluckas** [comment]
There are two problems.
1) When CustomTabs are started, HandleRedirectActivity goes to the background and can get killed by the OS. That will loose your state (`customTabStarted`) and the activity starts misbehaving.

You could work around that by using savedInstanceState to save it. I just don't  think it is needed at all.

2) When `HandleRedirectActivity` comes to foreground, the originating activity goes to the background and can get killed by the OS. When, after authentication the originating activity gets recreated, it will re-register a complete new `AndroidCodeAuthFlowFactory`, which creates new `resultFlow` and eventually emit the result to that new resultFlow while the original coroutine is still suspended, waiting for an emission to the original `resultFlow`.

You could work around that by
- Using your `/feat-factory` branch
- Not recreate `AndroidCodeAuthFlowFactory` when the activity gets restarted. Create it once as singleton e.g in activity's companion object or better through DI.
- Do not create the `resultFlow` with each activity recreation, but make it a property of `AndroidCodeAuthFlowFactory` and pass it as parameter to `registerForActivityResultSuspend` so the emission of the final result goes to the right flow resuming the right coroutine
- You should probably set resultFlow back to null after getting it's value so it can be reused.

**Comment by uliluckas** [comment]
Feel free to checkout this draft of how a fix could look:
[#24](https://github.com/kalinjul/kotlin-multiplatform-oidc/pull/24)

**Comment by kalinjul** [comment]
Thanks for this detailed description.
I will use your suggestions for the next version.

This still will be an issue in the included sample app as it is not using DI. Even keeping the AuthFlowFactory will not suffice as the received tokens will not be handled by the presenter at this time.
But i guess this is up to the user's app architecture.

**Comment by uliluckas** [comment]
> Thanks for this detailed description.
>I will use your suggestions for the next version.

Cool!

> This still will be an issue in the included sample app as it is not using DI. Even keeping the AuthFlowFactory will not suffice as the received tokens will not be handled by the presenter at this time.
But i guess this is up to the user's app architecture.

Yes, you are right. I did not fix the samples or README.
But you could hint the user in the README at having only a single instance of AuthFlowFactory per activity and put it in the activitiy's companion object in your sample:

```
class MainActivity : ComponentActivity() {

    companion object {
        val codeAuthFlowFactory = AndroidCodeAuthFlowFactory(useWebView = false)
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        codeAuthFlowFactory.registerActivity(this)e
        setContent {
            MainView(
                codeAuthFlowFactory
            )
        }
    }
}
```

**Comment by uliluckas** [comment]
>Thanks for this detailed description.
I will use your suggestions for the next version.

Do you have any time line for your next release?

**Comment by kalinjul** [comment]
> But you could hint the user in the README at having only a single instance of AuthFlowFactory per activity

You're right, i will add this.

> and put it in the activitiy's companion object in your sample:

Actually in the sample app it doesn't help, because it does use Presenters that are scoped to the backstack, so the app does not care for the result anymore once the activity is gone.
You would need an application scoped instance that cares about authentication to tackle this. I currently consider this out of scope of the sample :)

> Do you have any time line for your next release?

Maybe next week, I'd like to test the changes in a real-world app first. You can try 0.9.0-SNAPSHOT from
maven("https://s01.oss.sonatype.org/content/repositories/snapshots/") if you like.

**Comment by uliluckas** [comment]
Thanks for the snapshot. currently testing it.

**Comment by uliluckas** [comment]
Works nicely. Thanks.
