### ISSUE TITLE
Closing the customtab on Android reopens it instead of returning to the app

### ISSUE THREAD

**Issue by maicol07** [kalinjul/kotlin-multiplatform-oidc#30]
Hi,
when the authorization request is sent and the Chrome custom tab is opened, if the user closes or minimizes it, it reopens and can't return to the app.

**Comment by kalinjul** [comment]
Hi, thanks for reporting, i can confirm the issue in the develop branch.
Seems that i introduced this bug in 0.9.0, you can check if 0.8.2 works for you.

I will look into it and fix the issue.

**Comment by kalinjul** [comment]
Should be fixed in [0.9.1](https://github.com/kalinjul/kotlin-multiplatform-oidc/releases/tag/0.9.1)
