### ISSUE TITLE
Security vulnerability detected by Google Play

### ISSUE THREAD

**Issue by maicol07** [kalinjul/kotlin-multiplatform-oidc#35]
Hi,
I got the following email from Google when I submitted my app:
![image](https://github.com/kalinjul/kotlin-multiplatform-oidc/assets/9463142/fe7ece2f-8592-4232-bc5a-f7dd0e516ad4)

The link points to this article: https://support.google.com/faqs/answer/9267555
Can you check if the vulnerability is present in the library?
Thanks

**Comment by kalinjul** [comment]
Hi, thanks for reporting!
I will try to add a mitigation, see #36.
Could i ask you to try with a snapshot once it is ready?

Kind Regards,
Julian

**Comment by maicol07** [comment]
Yes, of course!
Thank you

**Comment by maicol07** [comment]
I've tried to submit a build to Play Store and I haven't received any email. So I guess this is fixed!
Thank you!
