### ISSUE TITLE
Publishing to Github packages

### ISSUE THREAD

**Issue by dima-ko** [kalinjul/kotlin-multiplatform-oidc#37]
Hi. I am trying to publish a fork of your library to Gihub packages. Publishing seems to work fine, but I am struggling with collecting all the proper artefacts (for example I can't manage to publish oidc-appsupport.jar and depenedency libraries)
Can you give a hint of what I should do to achieve that?

**Comment by kalinjul** [comment]
Hi,
I'm sorry, i don't have experience with publishing to github packages, as i only publish to maven central.
That said - using the same maven publish configuration as in my repository, all required artifacts should be published.

Kind Regards,
Julian
