### ISSUE TITLE
Automatic discovery with client.discover() fails on iOS with HTTP result code 406

### ISSUE THREAD

**Issue by lsh-silpion** [kalinjul/kotlin-multiplatform-oidc#39]
Hi Julian,

automatic discovery on iOS using `client.discover()` fails with HTTP result code 406:

`Error Domain=KotlinException Code=0 "Could not download discovery document: HttpResponse[http://SLPN-NB-LASH.local:8571/auth/realms/idp/.well-known/openid-configuration, 406 Not Acceptable]"`

Steps to reproduce:

Run https://github.com/gematik/ref-idp-server using Docker like described here: https://github.com/gematik/ref-idp-server?tab=readme-ov-file#idp-server-as-docker-image : 

Use existing image from docker hub

https://hub.docker.com/repository/docker/gematik1/idp-server

Start container

$ docker run --rm -it -p 8571:8080 gematik1/idp-server

Smoke test: get discovery document

$ curl http://localhost:8571/auth/realms/idp/.well-known/openid-configuration 

(note here: no accept headers added!)

Use the following iOS Swift Code to reproduce the error:

```swift
struct IDPClient {
    let client: OpenIdConnectClient
    let tokens: AccessTokenResponse?
    let tokenstore: KeychainTokenStore?
//    let oldAccessToken: String
    
    init() async {
        client = await IDPClient.initClient()
        tokens = await IDPClient.initTokens(client: client)
        tokenstore = await IDPClient.initTokenstore(tokens: tokens)
    }

    // Create OpenID config and client:
    @MainActor
    private static func initClient() async -> OpenIdConnectClient {
        let client = OpenIdConnectClient(
            config: OpenIdConnectClientConfig(
                discoveryUri: "http://SLPN-NB-LASH.local:8571/auth/realms/idp/.well-known/openid-configuration",
                
                /*
                 * If you provide a Discovery URI, you may skip the endpoint configuration
                 */
                //                    endpoints: Endpoints(
                //                        tokenEndpoint: "<tokenEndpoint>",
                //                        authorizationEndpoint: "<authorizationEndpoint>",
                //                        userInfoEndpoint: nil,
                //                        endSessionEndpoint: "<endSessionEndpoint>"
                //                    ),
                endpoints: Endpoints(
                    tokenEndpoint: nil,
                    authorizationEndpoint: nil,
                    userInfoEndpoint: nil,
                    endSessionEndpoint: nil
                ),
                clientId: "eRezeptApp",
                clientSecret: "<clientSecret>",
                scope: "openid e-rezept",
                codeChallengeMethod: .s256,
                redirectUri: "http://redirect.gematik.de/erezept"
            )
        )
        
        /*
         * and call discover() on the client to retrieve the endpoint configuration.
         */
        do {
            try await client.discover()
        } catch {
            //handle error
            print(error)
        }
        
        return client
    }

    // Request access token using code auth flow:
    @MainActor
    private static func initTokens(client: OpenIdConnectClient) async -> AccessTokenResponse? {
        let flow = CodeAuthFlow(client: client)
        
        var tokens: AccessTokenResponse? = nil
        do {
            tokens = try await flow.getAccessToken()
        } catch {
            print(error)
        }
        
        return tokens
    }

    // TokenStore
    @MainActor
    private static func initTokenstore(tokens: AccessTokenResponse?) async -> KeychainTokenStore {
        let tokenstore = KeychainTokenStore()
        
        if (tokens != nil) {
            do {
                try await tokenstore.saveTokens(tokens: tokens!)
            } catch {
                print(error)
            }
        }
        
        return tokenstore
    }
}
```

replace `SLPN-NB-LASH.local` in the above code with the hostname or IP-address of the machine you're running the Docker image on — it will be called from your iOS device, so `localhost` is probably not an option.

Please let me know if you need further information!

Thanks,

Lars

**Comment by kalinjul** [comment]
Hi Lars,
thanks for the detailled description.
I quickly ran curl against another website, it looks like curl adds `Accept: */*` by default. You can check with curl -v.

One can also suppress the default header:
`curl -vH 'Accept:' http://localhost:8571/auth/realms/idp/.well-known/openid-configuration`

I haven't yet checked with your IDP image, but I'm quite sure we'll need to add an Accept header for your case.

Which is of course correct, we should provide the appropriate header. I'm just doing JSON decoding outside of ktor, so it didn't set the header automatically. I'll provide a fix soon. You could continue without using discovery in the mean time.

Kind regards,
Julian

**Comment by lsh-silpion** [comment]
Just checked with `curl -vH 'Accept:' http://localhost:8571/auth/realms/idp/.well-known/openid-configuration` against the Gematik-IDP, it worked as well.

**Comment by kalinjul** [comment]
Hmm.. and I just added logging, started discovery on iOS and it sends:
```
METHOD: HttpMethod(value=GET)
COMMON HEADERS
-> Accept: */*
-> Accept-Charset: UTF-8
CONTENT HEADERS
-> Content-Length: 0
BODY Content-Type: null
```

Must be something else than

**Comment by kalinjul** [comment]
Oh check out this interceptor i found in the spring code of your IDP:
https://github.com/gematik/ref-idp-server/blob/master/idp-server/src/main/java/de/gematik/idp/server/validation/clientSystem/ClientSystemInterceptor.java

https://github.com/gematik/ref-idp-server/blob/e4d0b1114046493f175deaf79d24aa77dff1ce2e/idp-server/src/main/java/de/gematik/idp/server/validation/clientSystem/ClientSystemInterceptor.java#L54

**Comment by lsh-silpion** [comment]
Hmm, interesting. They seem to block certain clients based on the user agent. I don't know why they're doing this, the ways of the Gematik are manyfold and unexplained … ; )

However, my task is it to get our app working with the Gematik-Code, without having any influence on it. I was hoping I can use your framework for this, but I would understand if you don't want to support non standard behaviour on the server side.

**Comment by lsh-silpion** [comment]
Looks like they barf on the missing user agent. Maybe for now just any user agent would do … at least we could try.

**Comment by kalinjul** [comment]
I'm not sure if adding a user agent in the library is a good thing.
But as I said, you can provide a custom Ktor HTTP client - which only works on kotlin-side for now - and use the user agent plugin: https://ktor.io/docs/client-user-agent.html

It would be nice to have support for this in Swift, but the more i think about it, the less feasible it seems to be.
We'd need a mapping for all required classes/initializers, currently, you simply cannot instantiate a Ktor Http Client from Swift. Also, I don't want to include all possible ktor plugins as dependencies.

Maybe we can include some simple API for adding custom headers as we already have in the other calls (getAccessToken(), refreshToken(), endSession()).

**Comment by lsh-silpion** [comment]
I don't think, a fixed user agent would be a good thing. But maybe there could be a configurable optional String setting in `OpenIdConnectClientConfig` so that when you need a user agent you can set it, otherwise it won't be installed (parameter is nil). How about that? 

And later, when we add Android support to our app we'll probably will need a user agent for okHttp too …

**Comment by kalinjul** [comment]
> And later, when we add Android support to our app we'll probably will need an user agent for okHttp too …

Well, as i said, you can pass a custom http client and add plugins as required. If you plan on adding Android and already use multiplatform, why do you implement Authentication in swift then?

For Swift only, i will check if I can add something in the future.

**Comment by kalinjul** [comment]
Check out 0.9.3, there's a new api to install custom ktor plugins from Swift that can add headers:
https://github.com/kalinjul/OpenIdConnectClient/blob/main/README.md

```
let client = OpenIdConnectClient(
    httpClient: OpenIdConnectClient.companion.DefaultHttpClient.config(block: { config in
        config.installClientPlugin(
            name: "customheader",
            onRequest: { requestBuilder, content in
                requestBuilder.headers.append(name: "User-Agent", value: "oidcclient")
            },
            onResponse: {_ in},
            onClose: {}
        )
    }),
    config: ...
)
```

You can also pass a configure block to specific calls to add headers. But if the lib decides it needs to do automatic discovery before calling an endpoint, that discovery will be called without the custom configure block, so prefer a ktor plugin for things like adding a user agent.
