### ISSUE TITLE
Amr should be an array of strings instead of string.

### ISSUE THREAD

**Issue by nripendra** [kalinjul/kotlin-multiplatform-oidc#52]
Hello. Thank you for the awesome project! Really well implemented. 

I am reporting about discrepancies between the implementation of amr claim from the specs. I have a server responding with the amr claim according to the specs, hence cannot use the built in Jwt parser provided by this library.

Implementation:

https://github.com/kalinjul/kotlin-multiplatform-oidc/blob/3d8e3ae66a44f413d0b9ef9b5283b172aef80210/oidc-core/src/commonMain/kotlin/org/publicvalue/multiplatform/oidc/types/IdToken.kt#L30

Specs:
https://www.rfc-editor.org/rfc/rfc8176

Since, no one has complained about it so far, I am assuming that there are implementations that represents amr as string instead of array. 

Could this be changed to  `Any?` instead of `String?`, and deal with both the scenarios?

**Comment by kalinjul** [comment]
Hi, thanks for reporting this, it will be fixed in the next release.
