### ISSUE TITLE
Configuration to avoid `auto-login`

### ISSUE THREAD

**Issue by mboron** [kalinjul/kotlin-multiplatform-oidc#53]
It would be useful if the client can be configured to send the `prompt=login` parameter in the authorisation request.

This can force the authorization server to prompt the end-user for re-authentication.

**Comment by kalinjul** [comment]
I will add a possibility to configure the auth url (PR #55)
If only my IDP would support this! Instead, it just ignores the prompt parameter.

**Comment by kalinjul** [comment]
Configuring the auth url is available in 0.10.0
