### ISSUE TITLE
Unable to modify Parameter in Authorization Request

### ISSUE THREAD

**Issue by gcaguilar** [kalinjul/kotlin-multiplatform-oidc#58]
Currently, I am encountering an issue when attempting to modify the redirect_uri parameter to redirect_url using `configureTokenExchange` within the` getAccessToken()` function of the CodeAuthFlow class. It seems that the parameters modification is not being applied correctly when making the authorization endpoint call.
I have been able to modify the headers successfully.
```
val flow = authFlowFactory.createAuthFlow(client)
flow.getAccessToken(
    configureTokenExchange = {
        this.url {
            parameters.remove("redirect_uri")
            parameters.append("redirect_url", "newParameter")
        }
    }
)
```
Despite this configuration, the redirect_url parameter does not appear to be correctly included in the request sent to the authorization endpoint. This discrepancy prevents the successful exchange of authorization code for an access token.

I appreciate any guidance or suggestions to resolve this issue effectively. Thank you.

**Comment by kalinjul** [comment]
Hi, 
this is a POST request using form parameters.
If you want to alter the form parameters, i guess you have to set the whole body yourself using 
`setBody(FormDataContent(formParameters))`
You may cast the existing body to FormDataContent, get all existing parameters from there and set a new body.

But the easiest way would propably be to use the correct redirect url in the first place :)
You can also just alter the redirectUri in the config used by the OpenIdConnectClient right before you cann getAccessToken.
