### ISSUE TITLE
Firefox (Android) not handling redirect

### ISSUE THREAD

**Issue by DatL4g** [kalinjul/kotlin-multiplatform-oidc#61]
Seems like the redirect isn't handled with the Firefox browser on Android.
Chromium based browsers work fine.

https://github.com/DatL4g/Burning-Series/issues/83

```kotlin
OpenIdConnectClient {
	endpoints {
		authorizationEndpoint = "https://github.com/login/oauth/authorize"
		tokenEndpoint = "https://github.com/login/oauth/access_token"
	}

	clientId = Sekret.githubClientId(BuildKonfig.packageName)
	clientSecret = Sekret.githubClientSecret(BuildKonfig.packageName)
	scope = "read:user"
}
```

Callback URI:

```kotlin
/** burningseries://github */

addManifestPlaceholders(
	mapOf("oidcRedirectScheme" to "burningseries")
)
```

**Comment by kalinjul** [comment]
It seems this is not related to this library, i found this post: 
https://stackoverflow.com/questions/49397439/appauth-android-https-scheme-work-with-firefox-and-other-browser
