### ISSUE TITLE
Question about compatibility with specific api

### ISSUE THREAD

**Issue by tSquaredd** [kalinjul/kotlin-multiplatform-oidc#66]
Will this library work for this auth flow? https://www.discogs.com/developers#page:authentication,header:authentication-oauth-flow.

Sorry if this is a silly question, not very familiar with implementing oauth flows.

**Comment by kalinjul** [comment]
I think this is not a silly question at all :)
Discogs seems to use OAuth 1.0, which is not targeted in this library. Honestly, i didn't even know it still exists.
So sadly the answer is no - we only support OpenIDConnect / OAuth 2.0 and only one specific flow ([Authorization Code Grant Flow](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1)), which is the most commonly used one.

**Comment by tSquaredd** [comment]
The Discogs API feels very outdated even just in terms of documentation so I am not surprised. 

Thank you!! Hopefully I will find a better API and will circle back on using this library. I was able to get the login page to load and generally using this library seemed really straightforward so thank you!!
