### ISSUE TITLE
Handle Null Refresh Token in Token Refresh Flow with Amazon Cognito

### ISSUE THREAD

**Issue by donadev** [kalinjul/kotlin-multiplatform-oidc#84]
## Description  

When issuing an OAuth2 token request with `grant_type=refresh_token` to servers like Amazon Cognito, a new `access_token` and optionally a new `id_token` are returned, but **no new `refresh_token`** is provided.  

In the current `TokenRefreshHandler` implementation, a new refresh token is explicitly expected in the response. If it’s not present (as is the case with Cognito), the `refresh_token` is set to `null`. This causes subsequent `grant_type=refresh_token` requests to fail, as the handler no longer has a valid refresh token to use.  

## Proposed Solution  
- Add a nullability check for the returned refresh token in the `TokenRefreshHandler`.  
- If the refresh token in the response is `null`, retain and reuse the previously used refresh token instead of removing it.  

## Steps to Reproduce  
1. Configure the application to use Amazon Cognito as the OAuth2 provider.  
2. Perform a `grant_type=refresh_token` token request.  
3. Observe that the returned `refresh_token` is `null`.  
4. Attempt another `grant_type=refresh_token` request — it will fail due to the null refresh token.  

## Expected Behavior  
The handler should retain the existing refresh token when the server does not return a new one, ensuring that subsequent refresh requests continue to work as expected.  

## Impact  
This issue causes token refresh flows to fail with providers like Amazon Cognito, disrupting functionality for applications relying on these flows.  

## Additional Notes  
This behavior aligns with Amazon Cognito's standard implementation, as it typically does not provide a new `refresh_token` with a refresh request. Adjusting the handler logic will ensure compatibility with Cognito and similar providers.  

Please consider prioritizing this fix to support a broader range of OAuth2 providers effectively.

**Comment by kalinjul** [comment]
You are correct, this is currently handled incorrectly.
As per [RFC 6749](https://www.rfc-editor.org/rfc/rfc6749.html#page-47):

   The authorization server MAY issue a new refresh token, in which case
   the client MUST discard the old refresh token and replace it with the
   new refresh token.

Thanks for the fix, i will release a fixed version asap.
